name: Lighthouse (incognito)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    concurrency:
      group: lighthouse-${{ github.event.pull_request.number || github.ref_name || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Build site
        run: npm run build

      - name: Start static server
        run: |
          npx http-server dist -p 8080 &
          npx wait-on http://localhost:8080

      - name: Run Lighthouse (desktop, incognito)
        run: |
          mkdir -p lighthouse
          npx lighthouse http://localhost:8080 \
            --preset=desktop \
            --chrome-flags="--no-sandbox --incognito" \
            --output=json \
            --output=html \
            --output-path=./lighthouse/report

      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: lighthouse/
